theme: jekyll-agency

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Bitrise 💜  
email      : your-email@example.com #this is also the email contact forms will go to
description: "Site description"
author     : Your Name
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  apps: 
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "home"
  -
    scope:
      type: "apps"
    values:
      layout: "publisher" # overrides previous default layout

markdown: kramdown

exclude:
  - app_data
  - create_collection.py
  - get_data.py
  - jekyll-agency.gemspec
  - LICENSE.txt
  - README.md
  - screenshot.PNG